### PR TITLE
fix warning about renamed method in django 1.8

### PR DESCRIPTION
**Pull request by jschneier**
@yakky

### CODE REVIEW

**Comment by spil-rkoopmans** [comment]
Can we get this merged?

**Comment by stefanfoulis** [comment]
@spil-rkoopmans thanks for the patch :-)
Could you add comments in the code so we know why this try/except exists? Especially for which Django versions it is.

**Comment by stefanfoulis** [comment]
Sorry, I meant @jschneier

**Comment by jschneier** [comment]
@stefanfoulis done and force pushed. Just want to confirm that filer is still supporting 1.4/1.5? If not then I can just rename the method and remove the workaround.

**Comment by yakky** [comment]
Thanks @jschneier !

**Pull request merged**
