### PR TITLE
fix a warning about renamed in Django 1.8 method

### PR DESCRIPTION
**Pull request by jschneier**
Hi, I'm using Django 1.7 and this is causing a warning right now. Thanks for the project!

### CODE REVIEW

**Comment by yakky** [comment]
As currently cmsplugin filer still supports Django 1.4 and 1.5 we cannot simply change the call to the newer one.

**Comment by jschneier** [comment]
So this is simply going to break in 1.8 then I think? What about
```python
parent = super(FilerPluginManager, self)
qs = getattr(parent, 'get_queryset', 'get_query_set')()
```

**Comment by jschneier** [comment]
Ah I see, cms 3.1 is going to drop support for the lower versions of cms and then this can be merged, cool.

**Comment by yakky** [comment]
A popular idiom is something like:

    def get_queryset(self):
        try:
            qs = super(FilerPluginManager, self).get_queryset()
        except AttributeError:
            qs = super(FilerPluginManager, self).get_query_set()
        ...

    get_query_set = get_queryset

I think we need a last version compatible with Django 1.4 / 1.5 to release the latest fixes and then drop older Django version compatibility

**Comment by jschneier** [comment]
Ah yeah mine would obviously break in super chains. Just up another PR with that idiom at #177 so going to close this.

**Pull request closed without merging**
